### ISSUE TITLE
Missing Table Structure

### ISSUE THREAD

**Issue by Pinusno** [jease/jease#127]
When I setup Jease build from source, then I have no data for the dropdown menu to create new content. I also tried to download the sample db, but it was not working. I could not Login with admin/admin and there was also only a 404 page at the root level. Do you have sample data? Because I am not sure, if it is the only missing data.

Many thanks,
Karsten

**Comment by ghaseminya** [comment]
Hi @Pinusno 
Are you pull last version of jease from git?
Which version of java do you have?
What is your java webserver?

**Comment by Pinusno** [comment]
Hi, thank you for your respond. unfortunately it is now too long time ago so that I even do not remember. But thank you anyway

**Comment by ghaseminya** [comment]
Sorry
Any problem and issue are welcome.
